apiVersion: v1
kind: Service
metadata:
  name: fru-api
  namespace: ${NAMESPACE}
  labels:
    app: fru-api
spec:
  # Internal service only; external access is via NGINX Ingress
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: fru-api

